language: node_js
cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '8'
  - 'node'

script:
  - 'npm run eslint'
  - 'npm run test'
  - 'npm run docs:clean'
  - 'npm run docs'
  - npm run travis-deploy-once "npm run deploy ${TRAVIS_PULL_REQUEST}"

after_script:
  - npm run cov:clean
  - npm run cov
  - npm run cov:publish

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  only:
    - master

env:
  global:
    - GH_REPO: "github.com/mamboer/fs.git"
    - secure: "KElmHq/XcjtD1aufQl1n6YOVtPHzHPqKAdKuiReklWIIN3W5jgH0pulsO2lS33pzerH2APDc6a0jgE/KOTZVPV4etmNJOTzQ4naUrQVmsAJj61vyADboiVUq6wOdEQT0ztLcpiRj1vRqmrFAjUiU6d7Xw/izQYcJbouTE1QPUroT1LE4hCaH5WidqkJ0lmYvUvGpbwzjfOTGfU+yYpoi8DDsXX19OsI7Ea+98giQmrVkz1hEP0zRmQ6l6oKKg0HJNHAUt3eJpTm7fLdl55LPM0maIz4h2eiboLgY6NUkDK4IylZmuSah8XsA4+RuLwpH+JG7IVrrCKuwsmXHqtCZ4ZXJfOxXVW6EihWZpZtw8lgKXa/Llxg55CjuHw/Jtm2M7jMvad99yj79K2FlbMf0labcjKbwLfBIYT9hMv61XVff8rcNGOk5/51NcNP8EbKKpzJe535YY50EZq6gbeYFC2xIXfc62ogbfQbBjH7TbKdUOS9Mq1lMsBPiS3d/QeQSVxxg2donm5nQ3206fU3v/pC7UmT2rnvLPeiir7KUFY3ix4Phr8VzJSWoUcDS9gYW2x2R/XFD5kmeiGi3rvo8iPLrgFPj8YBQMbCkkoVFMxEExeUXAZNlweHbZjifX47+w22fb/gpKmrE+LOYVDO9v4j/UsLCoFQC7G45otcKBkQ="
